name: Bug report
description: Make a clear and concise report for a bug.
labels: ["bug"]

body:
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: |
        Describe the bug / problem you are facing.
      placeholder: |
        E.G. Update to database not working for reports extraction command.
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: ToDo
      description: |
        Describe the tasks to do.
      placeholder: |
         E.G.:
         - [ ] first task
         - [ ] second task
           - [ ] sub task
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        How you became aware of the bug, who reported it.
      placeholder: |
        E.G.:
        - Apparently Bob got an error when running the model on the new image dataset.
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: |
        A set of things the assignee should not forget while doing the issue.
      placeholder: |
        E.G.:
        - Note that this code shall be removed anyway in a few weeks.